### PR TITLE
Fix samples

### PR DESCRIPTION
**Pull request by RLejolivet**
Couple of fixes to make all samples run:

- Added DB changelog to avoid failing at fr/mgargadennec/blossom/autoconfigure/core/LiquibaseAutoConfiguration.java:47
- Changed fr.mgargadennec.blossom.module.filemanager.FileContentDaoImpl because it was referencing "QFileContent" which doesn't exist anymore (?).

### CODE REVIEW

**Comment by mgargadennec** [comment]
Sadly, the QFileContent part is an error. Thoses Q-classes are generated by QueryDSL.

Your fix change the behavior of the method : instead of finding a QFileContent by a predicate on the fileId, you try to find a FileContent id with a File id, which will return no results.

**Comment by RLejolivet** [comment]
Indeed, my IDE was badly configured.

For future reference, I had to change the [following setting (thanks StackOverflow)](https://stackoverflow.com/questions/43613069/intellij-does-not-recognize-generated-sources#comment74279087_43613069). No idea if it's possible to hint that setting directly in the pom.xml...

**Comment by Glorfingol** [comment]
Normally, using maven clean installl and adding the generated sources to your classpath should be enough...

**Comment by RLejolivet** [comment]
@Glorfingol Yup, but I'm lazy and that's not very future-proof (in case new modules are made) :smile:

**Pull request merged**
